variable "vpc" {}
variable "env" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_rtid" {}
variable "app" {}
variable "bastion_cidr" {}
variable alb {}
variable "kms_arn" {}
variable "rds" {}
